---
- name: Process OS specific tasks
  include_tasks: "{{ include_file }}"
  vars:
    prefix: "{{ role_path }}/tasks/server/"
  with_first_found:
    - files: "{{ [prefix] | product(config.os[config.nodes[inventory_hostname].os].includes) | map('join') | list }}"
  loop_control:
    loop_var: include_file

- name: Disable firewall
  service:
    name: firewalld
    enabled: false
    state: stopped
